# Clippy configuration for high-quality Rust code
max-suggested-slice-pattern-length = 3
too-many-arguments-threshold = 5
type-complexity-threshold = 100
single-char-binding-names-threshold = 5
trivial-copy-size-limit = 4096

# Configure other behavior
cognitive-complexity-threshold = 30
too-many-lines-threshold = 100 